name: "button.sacha.house"
description: "https://button.sacha.house - Implementation of a stylized Minecraft button using Svelte as the frontend framework. Hosted on Netlify."
topics: []
homepage: ""
source:
  provider: gitlab
  namespace: "sachahjkl"
  path: "sachahjkl/button.sacha.house"
